show-failed-logs: True
keep-going: True
keep-incomplete: True
rerun-incomplete: True
printshellcmds: False
use-conda: True
use-singularity: True

# default-remote-provider: "GS"
# default-remote-prefix: "orcestradata/CCLE-Pharmacoset_Snakemake"
default-storage-provider: "gcs"
default-storage-prefix: "FILL IN YOUR BUCKET NAME HERE"
storage-gcs-keep-local: True

# When running on Kubernetes
jobs: 256