cores: 32
show-failed-logs: True
keep-going: True
keep-incomplete: True
rerun-incomplete: True
printshellcmds: False
use-conda: True
use-singularity: True

# When running on Kubernetes
jobs: 256       